public with sharing class WrapperSalesforceToSalesforceIntegration {
    
        @AuraEnabled 
		public String Id;	//0692t00000GJOmfAAH
        @AuraEnabled
		public String Title;	//Box integration
        @AuraEnabled
		public String FileExtension;	//png
        @AuraEnabled
		public Integer ContentSize;	//31535
        @AuraEnabled
        public cls_attributes attributes;
        @AuraEnabled 
		public String Name;

        class cls_attributes {
            public String type;	//ContentDocument
            public String url;	///services/data/v58.0/sobjects/ContentDocument/0692t00000GJOmkAAH&quot
        }
       
	
       
}